/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cc6ac0d6-b7db-4a2a-a31a-c8ad4004b92d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tDAq53Zby",
    "aws_user_pools_web_client_id": "2fv7sflmhue1lvqkblh9e9hhv4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gyllze77ffhg3fyxerdgnxzqwm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
